### PR TITLE
Displays grid of products

### PR DESCRIPTION
**Pull request by JAndresHJ**
## What's included?
- Grid of products taken from the mock file

## Screenshot
image

### CODE REVIEW

**Comment by marcoromerowizeline** [comment]
Hi Jorge. Thank you for your delivery. I notice that you moved the mock file from _/public/data_/ to _/src/utils/_, and you prefer **MaterialUI** instead of **styled-components**. Interesting. Excellent work, congrats!

**Comment by JAndresHJ** [comment]
Hi Marco, thank you for your comments and review!

**Comment by marcoromerowizeline** [comment]
I forgot to mention that it could be great if you add a key in `<ProductCard product={product} />` :)

**Comment by JAndresHJ** [comment]
> I forgot to mention that it could be great if you add a key in `<ProductCard product={product} />` :)

Hi Marco, you are right, it's something I noticed while working on the second deliverable. I've already added it to the next deliverable PR, here: https://github.com/JAndresHJ/react-redux-bootcamp-q2/pull/2

**Pull request merged**
